2022-12-20 16:44:53.327 +02:00 [ERR] Error: {"ClassName":"System.Exception","Message":"TaskResult","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at SpendLess.UnitTests.Tests.<>c.<<TaskResultMethodsWithExceptionsAreLoggedByInterceptor>b__40_0>d.MoveNext() in D:\\C#\\final\\SpendLess\\UnitTests\\Tests.cs:line 330\r\n--- End of stack trace from previous location ---\r\n   at SpendLess.Server.Interceptor.UnhandledExceptionLogger.InterceptAsync[T](Task`1 task) in D:\\C#\\final\\SpendLess\\Server\\Interceptor\\UnhandledExceptionLogger.cs:line 63","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Tests","WatsonBuckets":null}
