2022-12-20 17:16:59.200 +02:00 [ERR] Error: {"ClassName":"System.Exception","Message":null,"Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at SpendLess.UnitTests.Tests.<>c.<<TaskMethodsWithExceptionsAreLoggedByInterceptor>b__40_0>d.MoveNext() in D:\\C#\\final\\SpendLess\\UnitTests\\Tests.cs:line 337\r\n--- End of stack trace from previous location ---\r\n   at SpendLess.Server.Interceptor.UnhandledExceptionLogger.InterceptAsync(Task task) in D:\\C#\\final\\SpendLess\\Server\\Interceptor\\UnhandledExceptionLogger.cs:line 49","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Tests","WatsonBuckets":null}
